### ISSUE TITLE
Implement custom loss function in TF

### ISSUE THREAD

**Issue by rendorHaevyn** [rendorHaevyn/Project_WinLife#1]
Cusomised lost function is not working over vanilla TF loss function - need to address this.
[https://github.com/rendorHaevyn/Project_WinLife/blob/master/Reward%20Function.py](url)
[https://github.com/rendorHaevyn/Project_WinLife/blob/master/Sam/TF%20Attempt.py](url)

**Comment by Corpsecreate** [comment]
hmm whats this thingo

**Comment by opensourcegrappler** [comment]
rendor created for fun when the repo was created
