### ISSUE TITLE
missing data file ALL.csv

### ISSUE THREAD

**Issue by opensourcegrappler** [rendorHaevyn/Project_WinLife#2]
The CryptoAI.py file loads M30/ALL.csv but this file is not in the repo, please add.

**Comment by Corpsecreate** [comment]
You gotta use the data extraction code man!

**Comment by opensourcegrappler** [comment]
Ok cool, I couldn't tell with all this documentation we have... Haha

Please tell me that's not your private key for the poloniex API in that code..

**Comment by Corpsecreate** [comment]
It is yep! but the account is empty haha

**Comment by opensourcegrappler** [comment]
Gulp.. we should remove it.

**Comment by Corpsecreate** [comment]
You still at work? haha

**Comment by rendorHaevyn** [comment]
I left at 10, much more respectable than 1.

**Comment by Corpsecreate** [comment]
Mate, I'm getting some seriously amazing results here. This is nuts! So
exciting!
